version: '3'

services:
    mongo:
        image: mongo:6
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db

    blockchain:
        build: ./blockchain
        container_name: blockchain
        ports:
            - '7545:7545'

    backend:
        build: ./backend
        container_name: backend
        ports:
            - '3000:3000'
        depends_on:
            - mongo
            - blockchain
        environment:
            MONGO_URI: mongodb://mongo:27017/vehicles

    frontend:
        build: ./frontend
        container_name: frontend
        ports:
            - '3001:3000'
        depends_on:
            - backend

volumes:
    mongo-data:
